[package]
name = "sombra-index"
version = "0.0.0"
edition = "2021"

[dependencies]
sombra-types = { path = "../sombra-types" }
sombra-btree = { path = "../sombra-btree" }
sombra-pager = { path = "../sombra-pager" }
parking_lot = { workspace = true }
